---
title: "Valued Long Term Memories"
date: 2024-07-08T12:26:35+10:00
tags: ['opinion', 'education']
# draft: true
---

* Valued Knowledge and Skills for Long-Term Memory
** Purpose of Education
The selection of what is considered valuable knowledge and skills should be a deliberate process involving discussion and thought, rather than relying on historical precedents. This knowledge should be decided on by society, experts, educators, families, friends, and primarily by the individual student. We should avoid teaching what is irrelevant and inapplicable knowledge.
This decision is crucial because it significantly affects society, friends, family, associates, and ultimately has a profound impact on the student themselves.

*** What I think is valuable.
In general, I think the changes we aim to achieve in long-term memory should help individuals lead happy and successful lives while also having the desire and means to contribute positively to the society and world.

The below list details what I think students should know.

*** Desired Changes in Long-Term Memory
Here are some specific areas of knowledge and skills, that I think students might benefit from:
- Basic Needs: Students are able to obtain food and shelter (often through employment, but not exclusively).
- Health Maintenance: Students know how to maintain their mental and physical health (perhaps through knowledge of healthy eating, exercise and the health system).
- Resilience: Students are able to create a life that cannot easily disrupted by setbacks (e.g., having insurance if they their home burns in a fire or they are fired at work).
  - Self-Defence: Students can physically protect themselves from an attack.
  - Economic Success: Students can secure jobs and earn lots of money.
  - Status accumulation: Students can gain social status and power.
- Societal Systems: Students understand and be able to operate within (e.g., the political, historical, and economic systems of their society).
- Improving Societal Systems: Students know how to improve societal systems (e.g., through voting, advocacy, and other means).
- Community and Collaboration: Students are able to work well with others in their communities.
- Lifelong Learning: Students have a desire and ability to continue learning throughout their lives in order to adapt to new situations.
- Rational Decision-Making and Truth seeking: Students are capable of making rational decisions to ensure a robust quality of life.
- Meta-cognition: Students are able to think about their thinking, recognise cognitive biases and fallacies, and identify these in themselves.
- Hedonism: Students know how to have as much fun as possible through learning what they love to do (e.g., dancing, telling jokes, eating, cooking, travelling)

You might disagree with my thoughts above, and I would love to discuss what you think is valuable knowledge?
