---
title: "Resume"
date: 2024-05-02T14:32:51+10:00
tags: ['learning', 'resume']
---
* Noah Johnstone
-----
** OBJECTIVE
Looking to draw together technical, creative, and communicative skills to drive education innovation. Bringing a positive attitude, motivated by humility, clarity, and respect, in all that I do.

** ATTRIBUTES
- *Growth Mindset*: committed to ongoing learning from successes and failures
- *Humility*: cognisant of the complexity of teaching and software development and open to feedback
- *Resilience*: demonstrated tenacity, patience, and initiative in challenging environments
- *Analytical*: striving to incorporate evidence-based practices and engage in regular self-reflection

** EDUCATION
- Masters of Teaching (Secondary) (Leading Learning) Teach For Australia: ACU. 2021-22.
- Bachelor of Advanced Computing (Honours): ANU. Architecture & Systems Speciality 2016-20.
- Cambridge ESOL Level* CELTA QCF: RMIT. 2014. Qualified ESL teacher.
- Bachelor of Arts: University of Melbourne. Linguistics Major + Psych Minor. 2012-15.
- CERT IV In Visual Arts & Contemporary Craft, RMIT. 2012.

** RELEVANT WORK HISTORY

- Digital Technology Teacher, Sophia Mundi (VIC), Jan 2024 - Present.
- Digital Technology Teacher, Elevation Secondary College (VIC), Jan 2023 – Dec 2023.
- Digital Tech, Numeracy & English Teacher, Penguin District School (TAS), Jan 2021 – Dec 2022.
- Club Development Officer (ACT), ANU Sport, Mar 2018 – Sep 2020.
- Head/Assistant Teacher (ACT), Code Camp, Jan 2018 & 2019.
- Client and Project Manager for the ANU Tech-Launcher project (ACT), Feb 2018 – Sep 2019.
- Delivery Driver (ACT), 2016-2017.
- Various Hospitality (VIC), 2011-2015.
